version: '3.8'

services:
  # =======================================================
  # SIMULATED CLIENT 1: Alpine Property Management
  # =======================================================
  alpine_rental_pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mock_client_alpine_prod
    restart: always
    networks:
      - alpine_isolated_net
    volumes:
      - /var/lib/automation_data/client_alpine:/root/database
    environment:
      - STRIPE_SECRET_KEY=sk_test_51TkdCZBG28IMaYJ19B2J54SGor6Wr8tl1L7O2RV22BOfPKS9gJEyzgAwrok64jawNsgWh4i2VE4AO64UhPojXVvc00BdBxh7gS
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1518495286572613724/pUsBHrLtTPusg008X3ePI8IwF4kBPWXFBWO8qWdpywnVefCkJx0htUCGOYbjedMu0__n
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  # =======================================================
  # SIMULATED CLIENT 2: Apex Commercial Distributors
  # =======================================================
  apex_wholesale_pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mock_client_apex_prod
    restart: always
    networks:
      - apex_isolated_net
    volumes:
      - /var/lib/automation_data/client_apex:/root/database
    environment:
      - STRIPE_SECRET_KEY=sk_test_51TkdCZBG28IMaYJ19B2J54SGor6Wr8tl1L7O2RV22BOfPKS9gJEyzgAwrok64jawNsgWh4i2VE4AO64UhPojXVvc00BdBxh7gS
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1518495286572613724/pUsBHrLtTPusg008X3ePI8IwF4kBPWXFBWO8qWdpywnVefCkJx0htUCGOYbjedMu0__n
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

networks:
  alpine_isolated_net:
    driver: bridge
  apex_isolated_net:
    driver: bridge
